### ISSUE TITLE
Count() question

### ISSUE THREAD

**Issue by rboarman** [craiggwilson/fluent-mongo#11]
Not knowing where to ask questions, I posted on SO:

http://stackoverflow.com/questions/6273122/fluent-mongo-count-performance

Is there a better place to ask questions?

**Comment by craiggwilson** [comment]
I've answered your question there, but yes, it will get sent the server and executed.

**Comment by rboarman** [comment]
Wow, that was fast!

Thanks!

Similarly, how can I support Remove using AsQueryable?

```
    public void Remove<TEntity>( Expression<Func<TEntity, bool>> criteria) where TEntity : class
    {
        this.GetQuery<TEntity>()AsQueryable().Remove(criteria);
    }
```

The above snippet does not work obviously.

Thanks again!

Rick

-----Original Message-----

**Comment by craiggwilson** [comment]
Currently that is not available and probably won't be in the form you are using it.  In my plans is to write a layer on top of the driver to abstract away some of the gotcha's and remove would be a part of that.

**Comment by rboarman** [comment]
I was wondering if there has been any progress on this limitation? Creating a repository layer using FluentMongo without being able to remove or update documents is proving troublesome. Perhaps I missed a way to handle this while maintaining a proper repository pattern?

```
public interface IRepository : IDisposable
{
    IQueryable<T> All<T>() where T : class, new();

    void Delete<T>(Expression<Func<T, bool>> expression)
        where T : class, new();

    void Update<TEntity>(TEntity entity) where TEntity : class, new();
}
```
