### ISSUE TITLE
Update to mongo csharp driver 1.1

### ISSUE THREAD

**Issue by jonnii** [craiggwilson/fluent-mongo#12]
I downloaded the source and compiled it against the latest mongo csharp driver and all the tests pass with the exception of the regex ones, but I believe this is because the way the driver handles these has changed. Would it be possible to publish a new version of the package with the dependencies updated?

**Comment by craiggwilson** [comment]
Absolutely.  I don't have much time right now, so if you'd like to do the update and make sure all the tests pass and send me a pull request, I'll pull it in and publish a new package.
