### ISSUE TITLE
Package version not current when installed with Nuget

### ISSUE THREAD

**Issue by antoineleclair** [craiggwilson/fluent-mongo#15]
I just updated the Nuget packages I have in my project, including Fluent and Mongo C# driver. I have a lot of tests failing due to a Mongo driver version error at runtime:

```
System.IO.FileLoadException : Could not load file or assembly 'MongoDB.Driver, Version=1.0.0.4098, Culture=neutral, PublicKeyToken=f686731cfb9cc103' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

I have mongo c# driver 1.1 installed but my application is still looking for 1.0. Not sure yet if the bug comes from your package, but when investigating, I found out that the version number of the fluent mongo dll file was 1.0.1.1 instead of 1.1.0.0.

**Comment by antoineleclair** [comment]
As a temporary fix, I compiled from source and I took the dll to overwrite the one that came from NuGet. It worked. But the dll still says it's version 1.0.1.1.

**Comment by craiggwilson** [comment]
Yep, looks like I botched the packaging in the nuspec file.  I'll get it updated shortly.

**Comment by craiggwilson** [comment]
This should be fixed...

**Comment by antoineleclair** [comment]
Thanks!
