### ISSUE TITLE
$not placed in incorrect position.

### ISSUE THREAD

**Issue by dsludwig** [craiggwilson/fluent-mongo#18]
The $not meta-operator is placed in the incorrect position; for example:

``` c#
var foos = from foo in Collection.AsQueryable()
                  where !foo.Name.Contains("bar")
                  select foo;

```

results in a query of `{ $not : { Name : /bar/ } }` rather than the correct query of `{ Name : { $not : /bar/ } }`

See [MongoDB](http://www.mongodb.org/display/DOCS/Advanced+Queries#AdvancedQueries-Metaoperator%3A%7B%7B%24not%7D%7D)

**Comment by craiggwilson** [comment]
Are these not equivalent? Do the queries return different results or does the first one throw an error?

**Comment by dsludwig** [comment]
These do not appear to be equivalent. The first one doesn't throw an error, but it is unclear from the mongo docs what the semantics of the first query are. The first one does not return the expected result, while the second one does. A test case should illustrate:

``` c#
        [Test]
        [TestCase("J", 2)]
        [TestCase("Bob", 3)]
        public void Negated_String_StartsWith(string value, int expectedCount)
        {
            var people = (from p in Collection.AsQueryable()
                          where !p.FirstName.StartsWith(value)
                          select p).ToList();
            Assert.AreEqual(expectedCount, people.Count);
        }
```

This test fails for me with zero returned results.

It seems from the documentation that the $not operator only affects other operators such as regexes or $gt/$lt, etc., so the behaviour for the first query may be undefined; it that is the case, there definitely should be an error produced by mongodb.

**Comment by craiggwilson** [comment]
ok, I'll try and get this fixed...

**Comment by craiggwilson** [comment]
So, this is quite a bit harder than I had hoped.  nekresh has commited a change that might help, but I would sugges doing something more like where p.FirstName.StartsWith(value) == false instead.  Perhaps that will work.  This problem is related to how mongodb supports query operators and not all of them are supported in every context.
