### ISSUE TITLE
Problems with booleans

### ISSUE THREAD

**Issue by couellet** [craiggwilson/fluent-mongo#19]
I got a problem this morning with booleans. 

db.GetCollection<Person>("Person").AsQueryable()
         .Where(x => !x.Active)
         .ToList()

It returns nothing when it should, but if I do:

db.GetCollection<Person>("Person").AsQueryable()
         .Where(x => x.Active == false)
         .ToList()

It works!

This is certainly not an urgency, but it can cause some headaches ;)

My version of FluentMongo is 1.0.1.1

**Comment by craiggwilson** [comment]
This is the same issue another just raised about $not being placed in the wrong position.  I'm going to try a hack to fix this...

**Comment by nekresh** [comment]
I've issued a pull request for this problem (https://github.com/craiggwilson/fluent-mongo/pull/20)
I consider a not followed by a field to be the same as field == false

**Comment by craiggwilson** [comment]
I have merged in nekresh's pull request.
