### ISSUE TITLE
Problem querying embedded array using Any()

### ISSUE THREAD

**Issue by christiansparre** [craiggwilson/fluent-mongo#2]
Hi Craig

I'm having an issue when I try to query an embedded array. I'm trying to achieve something like the NestedQueryable_Any testmethod in MongoQueryTests.

The error is "QueryFailure flag set: invalid parameter: expected an object (response: { "$err" : "invalid parameter: expected an object", "code" : 10065 })"

The documents look like this

{
  "_id": "e058fb69ffca401ab96105eccad54a63",
  "Name": "Project 1",
  "CreatedUtc": "2011-02-16T08:32:38.7630000Z",
  "ModifiedUtc": "2011-02-16T08:32:38.7630000Z",
  "ClosedUtc": "0001-01-01T00:00:00.0000000Z",
  "MemberIds": [
    "206adab691e9493dbdb062f8440a3699",
    "13a3141fdfdc4521b0bd487cc2b3ef89"
  ]
}

I'm looking for any "project" where the "MemberIds" array contains a specific id

I hope you can help :)
## 

Christian

**Comment by craiggwilson** [comment]
I need to know about the C# code you are using to execute the code... can you post a sample?  In addition, it'd be great to know what was getting sent to the server.  You can turn profiling on in mongo and view the query.
