### ISSUE TITLE
Add support to the version 1.2 of the mongo-csharp-driver

### ISSUE THREAD

**Issue by eduardocampano** [craiggwilson/fluent-mongo#26]
Some methods changed their signature which translates in exceptions using the latest package. An example is the Count method in the IMongoQuery

**Comment by craiggwilson** [comment]
I have upgrade the driver reference.  However, I was unable to replicate your issues.  Please write a test showing the issue and I'll try and get it fixed.

**Comment by eduardocampano** [comment]
Thanks. Updated the package and now it works. The Count() method return value was changed to long in the 1.2 version and that seemed to be breaking fluent-mongo.
