### ISSUE TITLE
VisitMemberAccess and Interfaces - BsonClassMapSerializer cannot be used with type

### ISSUE THREAD

**Issue by ccm682** [craiggwilson/fluent-mongo#27]
This is the scenario:
-  I have a class that implements an interface IDomainObject, that defines a property (IsDeleted).
- I use a concrete class that implements this interface (public class User : IDomainObject).
- When I use this class in a Query<User> and try to do a lookup, I get the error "BsonClassMapSerializer cannot be used with type User". 

The problem is in the VisitMemberAccess method in FieldBinder.cs.  The first line is:

```
var declaringType = m.Member.DeclaringType;
```

Which returns IDomainObject, which is not supported by BsonClassMapSeriliazer.  I have fixed this with the follow code right after this line:

```
if (declaringType.IsInterface) {
                if (m.Expression is ParameterExpression) {
                    declaringType = ((ParameterExpression)m.Expression).Type;
                }
            }
```

There might be a better way of doing it, but it works.

**Comment by craiggwilson** [comment]
I cannot reproduce this issue.  If you want this looked at further, you're going to need to write a test showing the circumstance where this occurs.

**Comment by craiggwilson** [comment]
Closed due to no follow-up.
