### ISSUE TITLE
IEnumerable<Guid> Contains() not supported

### ISSUE THREAD

**Issue by josefresno** [craiggwilson/fluent-mongo#3]
Hi Craig,

We are testing this driver, and it looks like there is a problem with IEnumerable<Guid>() when using it as a Local Enumerable in a Contains() statement. 

IEnumerable of string works fine, just not Guid.

Here is a test:
            var ids = new List<Guid> {Guid.NewGuid()}.AsEnumerable();
            var results = Collection.AsQueryable().Where(x => ids.Contains(x.Id));

This results in the following error for us:

[NotSupportedException: The method Contains is not supported.]
   FluentMongo.Linq.Translators.JavascriptFormatter.VisitMethodCall(MethodCallExpression m) +3180
   FluentMongo.Linq.Expressions.ExpressionVisitor.Visit(Expression exp) +609
   FluentMongo.Linq.Expressions.MongoExpressionVisitor.Visit(Expression exp) +566
   FluentMongo.Linq.Translators.JavascriptFormatter.FormatJavascript(Expression expression) +74
   FluentMongo.Linq.Translators.MongoQueryObjectBuilder.VisitSelect(SelectExpression select) +413
   FluentMongo.Linq.Expressions.MongoExpressionVisitor.Visit(Expression exp) +346
   FluentMongo.Linq.Translators.MongoQueryObjectBuilder.VisitProjection(ProjectionExpression projection) +58
   FluentMongo.Linq.Expressions.MongoExpressionVisitor.Visit(Expression exp) +279
   FluentMongo.Linq.Translators.MongoQueryObjectBuilder.Build(Expression expression) +212
   FluentMongo.Linq.ExecutionBuilder.VisitProjection(ProjectionExpression projection) +90
   FluentMongo.Linq.Expressions.MongoExpressionVisitor.Visit(Expression exp) +279
   FluentMongo.Linq.ExecutionBuilder.Build(Expression expression, Expression provider) +53
   FluentMongo.Linq.MongoQueryProvider.BuildExecutionPlan(Expression expression) +304
   FluentMongo.Linq.MongoQueryProvider.Execute(Expression expression) +67
   FluentMongo.Linq.MongoQuery`1.GetEnumerator() +42
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +315
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58

It is also interesting to note that in order to get the 10Gen c# driver to work with a $in query for Guid, we had to do something like this:

Query.In("_id", BsonArray.Create(ids.Select(id => BsonValue.Create(id))))

(where ids is of type IEnumerable<Guid> )

Thanks,
-Joe

**Comment by craiggwilson** [comment]
Ok.  I'll have to look into this.  It should be supported already, but there is obviously something wrong.  Thanks for reporting.

**Comment by craiggwilson** [comment]
Ok, found the problem, but it resides in the official driver.  For now, instead of using a list, use an array.  Ultimately, underneath, we are calling BsonValue.Create.  It takes an object and succeeds when using an array, but fails with a List.  I'll try and get a fix in for this.

**Comment by craiggwilson** [comment]
Ok, fixed the issue.  It's a bit of a hack, but it's the only real option.

**Comment by josefresno** [comment]
Thanks!
