### ISSUE TITLE
Order By

### ISSUE THREAD

**Issue by sbond** [craiggwilson/fluent-mongo#32]
Hi Craig,

Sorry to create another Issue around Order by but I am having the same issue regarding performance.

I have a collection that contains roughly 65,000 records which I am exposing using OData. Obviously I dont want to allow all 65,000 records to be pulled down all at once so I restrict the returned records using Skip and Take. This works perfectly until I introduce the ability to Sort these records.

The I need to be able to sort the records prior to applying the take to ensure that the correct records are returned, however it would seem to me that the sort command does not get sent to Mongo rather it sorts the IQueryable result set.

For reference the query "?$format=json&$filter=startswith(Title,'S') eq true&$orderby=Title&$top=10"

With the Order By Applied takes 7 seconds to complete in the browser however the same call once the Order by has been removed takes no more than 624 milliseconds.

I might be missing something obvious but any help you are able to provide would be greatly appreciated.

Below is an example of the code in use, the adapter exposes an IQueryable result.

_adapter.All<Item>()
                                    .Where(whereClause)
                                    .OrderBy(i => i.Title)
                                    .Take(operation.TopCount.Equals(0) ? 20 : operation.TopCount)
                                    .Skip(operation.SkipCount.Equals(0) ? 0 : operation.SkipCount);

The All methods executes the following:

 _collection.FindAllAs<T>().AsQueryable();

Thanks

Stephen

**Comment by craiggwilson** [comment]
I don't think the problem is going to lie in FluentMongo.  My assumption is that the data services adapter is doing something with the orderings that make it inefficient.  

I'd suggest you set the profiling level to 2 on the mongodb server and then watch what queries come in.  Then you'll know if you are missing an index or some bad queries are getting generated.  Then you'll just need to snoop and see if it is FluentMongo or data services.

**Comment by nekresh** [comment]
Have you indexed your collection on the Title field ?

When you have a lot of records, MongoDB take a lot of time doing a fullscan on the collection when you don't have index. By creating an index on the Title field, MongoDB will go through the index instead which is a lot faster.

**Comment by sbond** [comment]
Hi,

I have turned verbose logging on for the Mongo Server to get a better understanding of what is going, from what I can see the data is retrieved in chunks of about 4500 records a time, see below for the log entries.

Thu Nov 03 10:39:34 [conn1] getmore ItemCatalogue.Items query: { $query: {}, $orderby: { Title: 1 } } cursorid:80334790518830 nreturned:4727 reslen:4194303 12ms
Thu Nov 03 10:39:34 [conn1] getmore ItemCatalogue.Items query: { $query: {}, $orderby: { Title: 1 } } cursorid:80334790518830 nreturned:4794 reslen:4194774 7ms
Thu Nov 03 10:39:35 [conn1] getmore ItemCatalogue.Items query: { $query: {}, $orderby: { Title: 1 } } cursorid:80334790518830 nreturned:4792 reslen:4194409 7ms
Thu Nov 03 10:39:36 [conn1] getmore ItemCatalogue.Items query: { $query: {}, $orderby: { Title: 1 } } cursorid:80334790518830 nreturned:4791 reslen:4195170 9ms
Thu Nov 03 10:39:36 [conn1] getmore ItemCatalogue.Items query: { $query: {}, $orderby: { Title: 1 } } cursorid:80334790518830 nreturned:4773 reslen:4194890 8ms
Thu Nov 03 10:39:37 [conn1] getmore ItemCatalogue.Items query: { $query: {}, $orderby: { Title: 1 } } cursorid:80334790518830 nreturned:4772 reslen:4194467 7ms
Thu Nov 03 10:39:37 [conn1] getmore ItemCatalogue.Items query: { $query: {}, $orderby: { Title: 1 } } cursorid:80334790518830 nreturned:4783 reslen:4195237 8ms

As you can see from the trace the filter is not getting translated and sent to Mongo. 

Should I be using a different query against the collection? Maybe its the use of the FindAllAs method that prevents a query being sent to Mongo?

I will keep looking and see if I can find any further information.

Thanks again for your input and a great project.

**Comment by nekresh** [comment]
I've missed that part when answering your question :

> The All methods executes the following:
> 
> ```
> _collection.FindAllAs().AsQueryable();
> ```

The method All should be :

```
_collection.AsQueryable();
```

The way you use it, it just convert the resulting IEnumerable<T> to an IQueryable<T> and use Linq-to-object on it, not fluent-mongo.
That's why the mongo request you're seeing is empty.

**Comment by sbond** [comment]
Ah, sorry I should have picked that up. Thankyou for your help.
