### ISSUE TITLE
Update dependency mongocharpdriver to 1.3

### ISSUE THREAD

**Issue by Fristi** [craiggwilson/fluent-mongo#36]
As the title says update to driver 1.3 :) Some fixes there. If you try to work with the 1.3 driver and 1.2 fluentmongo you'll get:

`The located assembly's manifest definition does not match the assembly reference`

FluentMongo tries to load the Bson.Driver version 1.2 while 1.3 is there.

**Comment by craiggwilson** [comment]
Okey dokey.  I've been remiss by not updating lately.  I'll try and get it done next week.  You're welcome to do it yourself and submit a pull if you need it sooner.

**Comment by craiggwilson** [comment]
This is done.

**Comment by Fristi** [comment]
Thanks man!
