### ISSUE TITLE
Problem with custom serializers

### ISSUE THREAD

**Issue by MiddleTommy** [craiggwilson/fluent-mongo#4]
I registered a custom decimal Serializer with mongo that Serializes decimals as Doubles.
When I do a linq query using say
p => p.cost  == 0.0M
p.cost is a decimal
The linq query does not translate the 0.0M correctly.

**Comment by craiggwilson** [comment]
Can you tell me what it is translating? As in, what query is getting sent to the server?

The linq provider isn't doing any kind of translation at that level.  Essentially, we are just building up a BsonDocument.  What you are doing there is equivalent to new BsonDocument("cost", 0.0m).  

It would also be great if you could write a test to demonstrate the problem.

**Comment by MiddleTommy** [comment]
I wrote a test. I modified the person object in your tests and added a decimal property called AnnualIncome.
 [Test]
        public void Linq_Decimal()
        {
            var people = Collection.AsQueryable().Where(x => x.AnnualIncome > 0.0M);

```
        var queryObject = ((IMongoQueryable)people).GetQueryObject();
        Assert.AreEqual(0, queryObject.Fields.ElementCount);
        Assert.AreEqual(0, queryObject.NumberToLimit);
        Assert.AreEqual(0, queryObject.NumberToSkip);
        Console.WriteLine(queryObject.Query.ToJson());
    }
```

Output from the test is as follows.
{ "$where" : "(this.AnnualIncome > \"0.0\")" }

**Comment by craiggwilson** [comment]
I have tracked down the issue.  Internally, the linq provider calls down into the driver to create values.  As such, it isn't the linq provider failing when using a decimal, but the driver itself.  Perhaps you should ensure that your custom serializer is registered properly.  You can test it out by calling BsonValue.Create(0.0m) before running a test.
