### ISSUE TITLE
The query is too complex to be processed by MongoDB. Try building a map-reduce query by hand or simplifying the query and using Linq-to-Objects.

### ISSUE THREAD

**Issue by surgicalcoder** [craiggwilson/fluent-mongo#41]
Having the above exception when I try to do a Count...

```
IQueryable<EmailQueue> emailQueues = repository.All<EmailQueue>().Where(x => x.DateScheduled.Value > DateTime.Now).Take(50);
            int count = emailQueues.Count();
```

If I iterate through the emailQueues, its fine, but if I do a LINQ Count(), then it throws the above exception.

Any ideas?

**Comment by craiggwilson** [comment]
what repository.All<EmailQueue> return?  For some reason, the engine is thinking that this is a map/reduce query.  Can you submit a test to prove the issue...?

**Comment by ygrinevich** [comment]
I have the same exception if execute the following query: 
Collection.AsQueryable().Where(criteria).Take(1).FirstOrDefault();
But, if I add ToList() before FirstOrDefault() it works good:
Collection.AsQueryable().Where(criteria).Take(1).ToList().FirstOrDefault();

**Comment by craiggwilson** [comment]
@ygrinevich:  why are you doing a Take 1 and a FirstOrDefault()...  The linq provider is probably seeing this and indicating that it cannot translate this into a mongo query.  However, it can translate a Take(1) or a FirstOrDefault() if they are specified independently.  

In other words, you are trying to do the same thing twice.  Get rid of the Take(1) and just use FirstOrDefault().

**Comment by ygrinevich** [comment]
Ah, I supposed that SetLimit() mongodb cursor's method executing only when queryObject.NumberToLimit property is set (when Take() part of select expression using). And another thing - exception throwing FluentMongo code.

MongoQueryObjectBuilder.cs line 156.
protected override Expression VisitSelect(SelectExpression select)
            {
                if (select.From.NodeType != (ExpressionType)MongoExpressionType.Collection)
                    throw new InvalidQueryException("The query is too complex to be processed by MongoDB. Try building a map-reduce query by hand or simplifying the query and using Linq-to-Objects.");

**Comment by craiggwilson** [comment]
Take does set the limit.  But FirstOrDefault will also set that limit (Because that is what it is supposed to do).

Yes, I see the where the exception is being thrown.  I'm not sure what you are trying to tell me...

**Comment by ygrinevich** [comment]
Nothing, just thank you! I got the answer.
