### ISSUE TITLE
Update to mongo csharp driver 1.3.1

### ISSUE THREAD

**Issue by jonnii** [craiggwilson/fluent-mongo#42]
In case you didn't see 1.3.1 has come out, any chance of rebuilding for 1.3.1?

Thanks,
Jonathan

**Comment by RobThree** [comment]
The nuget package claims to require driver version ≥ 1.3.0 but FluentMongo seems to require the specific 1.3.0 version. A workaround is to add some extra information to the App.Config / Web.Config but that's not ideal. Our MongoRepository depending on fluent-mongo fails: http://mongorepository.codeplex.com/workitem/774

**Comment by craiggwilson** [comment]
This should be updated to the latest driver version.  As to why it was failing, I'm not sure.  The references from FluentMongo to the driver are not version specific...

**Comment by RobThree** [comment]
Awesome! Thanks!

**Comment by jonnii** [comment]
Thanks craigg!
