### ISSUE TITLE
Bug when using Conjunction and Disjunction

### ISSUE THREAD

**Issue by ygrinevich** [craiggwilson/fluent-mongo#45]
When I execute the LINQ expression below

Collection.AsQueryable().Where(item => (item.FacebookId > 0 && item.FacebookId == user.FacebookId) || (item.Email == user.Email)).FirstOrDefault();
where user.FacebookId = 0, user.Email = "qwe@qwe.com"

the result query is: { "$or" : [{ "FacebookId" : NumberLong(0) }, { "Email" : "qwe@qwe.com" }] }
but should be: { "$or" : [{ "$and" : [{ "FacebookId" : { "$gt" : 0 } }, { "FacebookId" : NumberLong(0) }] }, { "Email" : "qwe@qwe.com" }] }

Does such LINQ expressions supported?

Thank you.

**Comment by asiraky** [comment]
ive had this same problem, currently fluentmongo doesnt support more than 2 'or' operators properly. this is due to the way it parses the expression, it would have to de-nest the entire expression, which i think is possible, but very vey difficult

**Comment by craiggwilson** [comment]
Yeah, this is kind of an issue.  Linq expression trees are binary, where the mongo $or operator allows for many and does NOT allow nesting of $or and $and operators.  This means its very difficult to figure out how exactly to organize the appropriate operations.

**Comment by asiraky** [comment]
Pretty sure the latest mongo does support nested or statements, but with limited index support.

**Comment by craiggwilson** [comment]
Yep, you are right.  I don't know what percentage of people using FluentMongo are on a server version < 2.0.   I need to overhaul the query generation anyway, so perhaps I can take this time to bring it up to 2.0 semantics. Hmmm...

**Comment by ygrinevich** [comment]
As I can see mongo going to add LINQ support to driver version 1.4 https://jira.mongodb.org/browse/CSHARP-91. I think you can help them ;)

**Comment by asiraky** [comment]
Well... that Jira says its not decided yet. And technically they already support linq, as in the mongocollections return an ienumerable<t> which can be queried via linq. I hope they mean it will be a proper iqueryable interface, but judging by the sound of that jira, it doesn't sound like they are committed to it.

**Comment by craiggwilson** [comment]
So, your query is odd.  Why would you ever do this:  where x.FacebookId != 0 && x.FacebookId > 21?  I mean, you can evaluate this locally...

Regardless, the query will now get serialized correctly with release 1.3.1.1.
