### ISSUE TITLE
Calling .Single causes an exception

### ISSUE THREAD

**Issue by rboarman** [craiggwilson/fluent-mongo#5]
When I call Single(), where there are no matching elements in the collection, I get an exception:

  InnerException: System.InvalidOperationException
       Message=Sequence contains no elements
       Source=System.Core
       StackTrace:
            at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
            at lambda_method(Closure , IEnumerable )
       InnerException:

I would expect a return value of null instead of an exception.

Should I be wrapping calls to Single with a try/catch to suppress the exception? Should I be calling SingleOrDefault instead?

Thank you!

**Comment by craiggwilson** [comment]
This is the expected response.  If you look at the docs on Single in System.Linq, Single will throw an exception when there are either no elements, or more than 1 element.

You can use SingleOrDefault, First(), or FirstOrDefault().
