### ISSUE TITLE
NuGet Install Error with 1.6 Driver

### ISSUE THREAD

**Issue by sphildreth** [craiggwilson/fluent-mongo#56]
Hi,

Installed fluent-mongo (its version 1.3.1.1) and mongocsharpdriver (its version 1.6) attempt to use AsQueryable() and this error;
-       $exception  {"Could not load file or assembly 'MongoDB.Driver, Version=1.3.1.4349, Culture=neutral, PublicKeyToken=f686731cfb9cc103' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"MongoDB.Driver, Version=1.3.1.4349, Culture=neutral, PublicKeyToken=f686731cfb9cc103"}    System.Exception {System.IO.FileLoadException}

I think this just means the NuGet package needs to be refreshed to use the latest mongocsharpdriver, right?

**Comment by craiggwilson** [comment]
Fluent Mongo is no longer a supported project.  I need to put something on the front page.  The official [mongo-csharp-driver](https://github.com/mongodb/mongo-csharp-driver) has full support of linq and should be used from now on.
